#ifndef _CASIOUSBUPLOADERVERSION_H_
#define _CASIOUSBUPLOADERVERSION_H_

#define CASIOUSBUPLOADER_VERSION_MAJOR 0
#define CASIOUSBUPLOADER_VERSION_MINOR 0
#define CASIOUSBUPLOADER_VERSION_RELEASE 3
#define CASIOUSBUPLOADER_VERSION_DATE_STRING "13 june 2016"

class CasioUsbUploaderVersion
{
public:
    static void printVersion();


};

#endif // _CASIOUSBUPLOADERVERSION_H_
